**Loading Data:**
Reading data from CSV, Excel, SQL databases, and other
formats using functions like pd.read_csv(), pd.read_excel(), and pd.read_sql().

In [3]:
import pandas as pd

In [4]:
file_path = '/content/train.csv'

# Use the read_csv() function to read the CSV file into a DataFrame
df = pd.read_csv(file_path)
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775
4         Storage                     Eldon Fold 'N Roll Cart System   22.3680
...           ...                                                ...       ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797       Phones                                        GE 30524EE4  235.1880
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 18 columns]

In [5]:
print(df.head())  # Display the first 5 rows
print(df.tail())  # Display the last 5 rows

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680
      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country     City  \
9795    SH-19975     Sally Hughsby  Corporate  United States  Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States   Toledo

         State  Postal Code   Region       Product ID         Category  \
9795  Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796      Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797      Ohio      43615.0     East  TEC-PH-10004977       Technology
9798      Ohio      43615.0     East  TEC-PH-10000912       Technology
9799      Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name    Sales
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.798
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.368
9797       Phones                                        GE 30524EE4  235.188
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.376
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.384

In [6]:
print(df.columns)  # Display column names
print(df.dtypes)   # Display data types

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [7]:
num_rows = len(df)
print("\n(b) Number of rows:", num_rows)

(b) Number of rows: 9800

In [8]:
averaged_values = df.mean()
print("\n(c) Averaged numbers:")
print(averaged_values)

(c) Averaged numbers:
Row ID          4900.500000
Postal Code    55273.322403
Sales            230.769059
dtype: float64

<ipython-input-8-9b10e6b26057>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  averaged_values = df.mean()

In [9]:
# (d) Max/min values
max_values = df.max()
min_values = df.min()
print("\n(d) Max values:")
print(max_values)
print("\n(d) Min values:")
print(min_values)

(d) Max values:
Row ID                                         9800
Order ID                             US-2018-169551
Order Date                               31/12/2017
Ship Date                                31/12/2018
Ship Mode                            Standard Class
Customer ID                                ZD-21925
Customer Name                    Zuschuss Donatelli
Segment                                 Home Office
Country                               United States
City                                           Yuma
State                                       Wyoming
Postal Code                                 99301.0
Region                                         West
Product ID                          TEC-PH-10004977
Category                                 Technology
Sub-Category                                 Tables
Product Name     netTALK DUO VoIP Telephone Service
Sales                                      22638.48
dtype: object

(d) Min values:
Row ID                                                           1
Order ID                                            CA-2015-100006
Order Date                                              01/01/2018
Ship Date                                               01/01/2016
Ship Mode                                              First Class
Customer ID                                               AA-10315
Customer Name                                        Aaron Bergman
Segment                                                   Consumer
Country                                              United States
City                                                      Aberdeen
State                                                      Alabama
Postal Code                                                 1040.0
Region                                                     Central
Product ID                                         FUR-BO-10000112
Category                                                 Furniture
Sub-Category                                           Accessories
Product Name     "While you Were Out" Message Book, One Form pe...
Sales                                                        0.444
dtype: object

In [10]:
missing_values = df.isnull().sum()
print("\n(e) Missing values per column:")
print(missing_values)

(e) Missing values per column:
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [11]:
print(df.head(10))  # Display the first 10 rows

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
5       6  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
6       7  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
7       8  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
8       9  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
9      10  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
5  Brosina Hoffman   Consumer  United States      Los Angeles  California
6  Brosina Hoffman   Consumer  United States      Los Angeles  California
7  Brosina Hoffman   Consumer  United States      Los Angeles  California
8  Brosina Hoffman   Consumer  United States      Los Angeles  California
9  Brosina Hoffman   Consumer  United States      Los Angeles  California

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage
5      90032.0   West  FUR-FU-10001487        Furniture  Furnishings
6      90032.0   West  OFF-AR-10002833  Office Supplies          Art
7      90032.0   West  TEC-PH-10002275       Technology       Phones
8      90032.0   West  OFF-BI-10003910  Office Supplies      Binders
9      90032.0   West  OFF-AP-10002892  Office Supplies   Appliances

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600
6                                         Newell 322    7.2800
7                     Mitel 5320 IP Phone VoIP phone  907.1520
8  DXL Angle-View Binders with Locking Rings by S...   18.5040
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000

In [12]:
# (a) Number of unique values per column
unique_values_count = df.nunique()
print("(a) Number of unique values per column:")
print(unique_values_count)

(a) Number of unique values per column:
Row ID           9800
Order ID         4922
Order Date       1230
Ship Date        1326
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              529
State              49
Postal Code       626
Region              4
Product ID       1861
Category            3
Sub-Category       17
Product Name     1849
Sales            5757
dtype: int64

In [13]:
# (b) Data types of values
data_types = df.dtypes
print("\n(b) Data types of values:")
print(data_types)

(b) Data types of values:
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [14]:
# (c) Group the dataset by a specific column and average other values
grouped_df = df.groupby('Order Date').mean()
print("\n(c) Grouped dataset by 'Order Date' and averaged other values:")
print(grouped_df)

(c) Grouped dataset by 'Order Date' and averaged other values:
                 Row ID   Postal Code       Sales
Order Date
01/01/2018  6805.300000  72860.000000  148.182800
01/02/2015   541.000000  54302.000000  468.900000
01/02/2017  5823.000000  56120.000000   80.985000
01/03/2015  6738.800000  70210.200000  220.315100
01/03/2016  8024.428571  65653.285714  234.596343
...                 ...           ...         ...
31/10/2017  5976.875000  66606.250000  468.812375
31/10/2018  7351.000000  65479.000000  174.642667
31/12/2015  5672.500000  25150.142857  375.233571
31/12/2016  3730.909091  60365.727273  125.576727
31/12/2017  3776.714286  67639.857143  104.538286

[1230 rows x 3 columns]

<ipython-input-14-05137ec58e33>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_df = df.groupby('Order Date').mean()

In [15]:
# (d) Extract the row with the highest average
highest_average_row = grouped_df.loc[grouped_df['Sales'].idxmax()]
print("\n(d) Row with the highest average in 'Sales':")
print(highest_average_row)

(d) Row with the highest average in 'Sales':
Row ID          9640.000
Postal Code    28027.000
Sales           4297.644
Name: 28/01/2016, dtype: float64

In [16]:
# Define the list of important columns in the desired order
important_columns = ['Order ID', 'Order Date', 'Ship Mode', 'Customer Name', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Region', 'City', 'State', 'Country', 'Postal Code', 'Segment', 'Customer ID']

# Rearrange the columns
df[important_columns]

# Display the DataFrame with important columns first
print(df[important_columns])

KeyError: ignored

In [17]:
# (a) Convert numerical values to float
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
df[numerical_columns] = df[numerical_columns].astype(float)

# (b) Lowercase all string values
string_columns = df.select_dtypes(include=['object']).columns
df[string_columns] = df[string_columns].apply(lambda x: x.str.lower())

# Display the modified DataFrame
print(df)

            Order ID  Order Date       Ship Mode     Customer Name  \
0     ca-2017-152156  08/11/2017    second class       claire gute
1     ca-2017-152156  08/11/2017    second class       claire gute
2     ca-2017-138688  12/06/2017    second class   darrin van huff
3     us-2016-108966  11/10/2016  standard class    sean o'donnell
4     us-2016-108966  11/10/2016  standard class    sean o'donnell
...              ...         ...             ...               ...
9795  ca-2017-125920  21/05/2017  standard class     sally hughsby
9796  ca-2016-128608  12/01/2016  standard class  cindy schnelling
9797  ca-2016-128608  12/01/2016  standard class  cindy schnelling
9798  ca-2016-128608  12/01/2016  standard class  cindy schnelling
9799  ca-2016-128608  12/01/2016  standard class  cindy schnelling

             Category Sub-Category  \
0           furniture    bookcases
1           furniture       chairs
2     office supplies       labels
3           furniture       tables
4     office supplies      storage
...               ...          ...
9795  office supplies      binders
9796  office supplies          art
9797       technology       phones
9798       technology       phones
9799       technology  accessories

                                           Product Name     Sales   Region  \
0                     bush somerset collection bookcase  261.9600    south
1     hon deluxe fabric upholstered stacking chairs,...  731.9400    south
2     self-adhesive address labels for typewriters b...   14.6200     west
3         bretford cr4500 series slim rectangular table  957.5775    south
4                        eldon fold 'n roll cart system   22.3680    south
...                                                 ...       ...      ...
9795  cardinal holdit! binder insert strips,extra st...    3.7980  central
9796           bic brite liner highlighters, chisel tip   10.3680     east
9797                                        ge 30524ee4  235.1880     east
9798           anker 24w portable micro usb car charger   26.3760     east
9799                sandisk cruzer 4 gb usb flash drive   10.3840     east

                 City       State        Country  Postal Code    Segment  \
0           henderson    kentucky  united states      42420.0   consumer
1           henderson    kentucky  united states      42420.0   consumer
2         los angeles  california  united states      90036.0  corporate
3     fort lauderdale     florida  united states      33311.0   consumer
4     fort lauderdale     florida  united states      33311.0   consumer
...               ...         ...            ...          ...        ...
9795          chicago    illinois  united states      60610.0  corporate
9796           toledo        ohio  united states      43615.0  corporate
9797           toledo        ohio  united states      43615.0  corporate
9798           toledo        ohio  united states      43615.0  corporate
9799           toledo        ohio  united states      43615.0  corporate

     Customer ID
0       cg-12520
1       cg-12520
2       dv-13045
3       so-20335
4       so-20335
...          ...
9795    sh-19975
9796    cs-12490
9797    cs-12490
9798    cs-12490
9799    cs-12490

[9800 rows x 15 columns]

In [18]:
import numpy as np
# Define the conditions for codifying "Sales" into "Sale Interest"
conditions = [
    (df['Sales'] < 100),
    (df['Sales'] >= 100) & (df['Sales'] < 500),
    (df['Sales'] >= 500)
]

# Define the values to assign for each condition
values = [1, 2, 3]

# Create a new column "Sale Interest" based on the conditions and values
df['Sale Interest'] = np.select(conditions, values, default=0)  # Default 0 for unclassified cases

# Display the modified DataFrame
print(df)

            Order ID  Order Date       Ship Mode     Customer Name  \
0     ca-2017-152156  08/11/2017    second class       claire gute
1     ca-2017-152156  08/11/2017    second class       claire gute
2     ca-2017-138688  12/06/2017    second class   darrin van huff
3     us-2016-108966  11/10/2016  standard class    sean o'donnell
4     us-2016-108966  11/10/2016  standard class    sean o'donnell
...              ...         ...             ...               ...
9795  ca-2017-125920  21/05/2017  standard class     sally hughsby
9796  ca-2016-128608  12/01/2016  standard class  cindy schnelling
9797  ca-2016-128608  12/01/2016  standard class  cindy schnelling
9798  ca-2016-128608  12/01/2016  standard class  cindy schnelling
9799  ca-2016-128608  12/01/2016  standard class  cindy schnelling

             Category Sub-Category  \
0           furniture    bookcases
1           furniture       chairs
2     office supplies       labels
3           furniture       tables
4     office supplies      storage
...               ...          ...
9795  office supplies      binders
9796  office supplies          art
9797       technology       phones
9798       technology       phones
9799       technology  accessories

                                           Product Name     Sales   Region  \
0                     bush somerset collection bookcase  261.9600    south
1     hon deluxe fabric upholstered stacking chairs,...  731.9400    south
2     self-adhesive address labels for typewriters b...   14.6200     west
3         bretford cr4500 series slim rectangular table  957.5775    south
4                        eldon fold 'n roll cart system   22.3680    south
...                                                 ...       ...      ...
9795  cardinal holdit! binder insert strips,extra st...    3.7980  central
9796           bic brite liner highlighters, chisel tip   10.3680     east
9797                                        ge 30524ee4  235.1880     east
9798           anker 24w portable micro usb car charger   26.3760     east
9799                sandisk cruzer 4 gb usb flash drive   10.3840     east

                 City       State        Country  Postal Code    Segment  \
0           henderson    kentucky  united states      42420.0   consumer
1           henderson    kentucky  united states      42420.0   consumer
2         los angeles  california  united states      90036.0  corporate
3     fort lauderdale     florida  united states      33311.0   consumer
4     fort lauderdale     florida  united states      33311.0   consumer
...               ...         ...            ...          ...        ...
9795          chicago    illinois  united states      60610.0  corporate
9796           toledo        ohio  united states      43615.0  corporate
9797           toledo        ohio  united states      43615.0  corporate
9798           toledo        ohio  united states      43615.0  corporate
9799           toledo        ohio  united states      43615.0  corporate

     Customer ID  Sale Interest
0       cg-12520              2
1       cg-12520              3
2       dv-13045              1
3       so-20335              3
4       so-20335              1
...          ...            ...
9795    sh-19975              1
9796    cs-12490              1
9797    cs-12490              2
9798    cs-12490              1
9799    cs-12490              1

[9800 rows x 16 columns]

In [19]:
# Normalize the "Sales" column
df['Sales'] = df['Sales'] / df['Sales'].max()
df

,Order ID,Order Date,Ship Mode,Customer Name,Category,Sub-Category,Product Name,Sales,Region,City,State,Country,Postal Code,Segment,Customer ID,Sale Interest
0,ca-2017-152156,08/11/2017,second class,claire gute,furniture,bookcases,bush somerset collection bookcase,0.011571,south,henderson,kentucky,united states,42420.0,consumer,cg-12520,2
1,ca-2017-152156,08/11/2017,second class,claire gute,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",0.032332,south,henderson,kentucky,united states,42420.0,consumer,cg-12520,3
2,ca-2017-138688,12/06/2017,second class,darrin van huff,office supplies,labels,self-adhesive address labels for typewriters b...,0.000646,west,los angeles,california,united states,90036.0,corporate,dv-13045,1
3,us-2016-108966,11/10/2016,standard class,sean o'donnell,furniture,tables,bretford cr4500 series slim rectangular table,0.042299,south,fort lauderdale,florida,united states,33311.0,consumer,so-20335,3
4,us-2016-108966,11/10/2016,standard class,sean o'donnell,office supplies,storage,eldon fold 'n roll cart system,0.000988,south,fort lauderdale,florida,united states,33311.0,consumer,so-20335,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,ca-2017-125920,21/05/2017,standard class,sally hughsby,office supplies,binders,"cardinal holdit! binder insert strips,extra st...",0.000168,central,chicago,illinois,united states,60610.0,corporate,sh-19975,1
9796,ca-2016-128608,12/01/2016,standard class,cindy schnelling,office supplies,art,"bic brite liner highlighters, chisel tip",0.000458,east,toledo,ohio,united states,43615.0,corporate,cs-12490,1
9797,ca-2016-128608,12/01/2016,standard class,cindy schnelling,technology,phones,ge 30524ee4,0.010389,east,toledo,ohio,united states,43615.0,corporate,cs-12490,2
9798,ca-2016-128608,12/01/2016,standard class,cindy schnelling,technology,phones,anker 24w portable micro usb car charger,0.001165,east,toledo,ohio,united states,43615.0,corporate,cs-12490,1
9799,ca-2016-128608,12/01/2016,standard class,cindy schnelling,technology,accessories,sandisk cruzer 4 gb usb flash drive,0.000459,east,toledo,ohio,united states,43615.0,corporate,cs-12490,1

In [20]:
# Delete "Postal Code" and "Customer Name" columns
df = df.drop(['Postal Code', 'Customer Name'], axis=1)
df

,Order ID,Order Date,Ship Mode,Category,Sub-Category,Product Name,Sales,Region,City,State,Country,Segment,Customer ID,Sale Interest
0,ca-2017-152156,08/11/2017,second class,furniture,bookcases,bush somerset collection bookcase,0.011571,south,henderson,kentucky,united states,consumer,cg-12520,2
1,ca-2017-152156,08/11/2017,second class,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",0.032332,south,henderson,kentucky,united states,consumer,cg-12520,3
2,ca-2017-138688,12/06/2017,second class,office supplies,labels,self-adhesive address labels for typewriters b...,0.000646,west,los angeles,california,united states,corporate,dv-13045,1
3,us-2016-108966,11/10/2016,standard class,furniture,tables,bretford cr4500 series slim rectangular table,0.042299,south,fort lauderdale,florida,united states,consumer,so-20335,3
4,us-2016-108966,11/10/2016,standard class,office supplies,storage,eldon fold 'n roll cart system,0.000988,south,fort lauderdale,florida,united states,consumer,so-20335,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,ca-2017-125920,21/05/2017,standard class,office supplies,binders,"cardinal holdit! binder insert strips,extra st...",0.000168,central,chicago,illinois,united states,corporate,sh-19975,1
9796,ca-2016-128608,12/01/2016,standard class,office supplies,art,"bic brite liner highlighters, chisel tip",0.000458,east,toledo,ohio,united states,corporate,cs-12490,1
9797,ca-2016-128608,12/01/2016,standard class,technology,phones,ge 30524ee4,0.010389,east,toledo,ohio,united states,corporate,cs-12490,2
9798,ca-2016-128608,12/01/2016,standard class,technology,phones,anker 24w portable micro usb car charger,0.001165,east,toledo,ohio,united states,corporate,cs-12490,1
9799,ca-2016-128608,12/01/2016,standard class,technology,accessories,sandisk cruzer 4 gb usb flash drive,0.000459,east,toledo,ohio,united states,corporate,cs-12490,1

In [21]:
# Delete duplicated records
df = df.drop_duplicates()
df

,Order ID,Order Date,Ship Mode,Category,Sub-Category,Product Name,Sales,Region,City,State,Country,Segment,Customer ID,Sale Interest
0,ca-2017-152156,08/11/2017,second class,furniture,bookcases,bush somerset collection bookcase,0.011571,south,henderson,kentucky,united states,consumer,cg-12520,2
1,ca-2017-152156,08/11/2017,second class,furniture,chairs,"hon deluxe fabric upholstered stacking chairs,...",0.032332,south,henderson,kentucky,united states,consumer,cg-12520,3
2,ca-2017-138688,12/06/2017,second class,office supplies,labels,self-adhesive address labels for typewriters b...,0.000646,west,los angeles,california,united states,corporate,dv-13045,1
3,us-2016-108966,11/10/2016,standard class,furniture,tables,bretford cr4500 series slim rectangular table,0.042299,south,fort lauderdale,florida,united states,consumer,so-20335,3
4,us-2016-108966,11/10/2016,standard class,office supplies,storage,eldon fold 'n roll cart system,0.000988,south,fort lauderdale,florida,united states,consumer,so-20335,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,ca-2017-125920,21/05/2017,standard class,office supplies,binders,"cardinal holdit! binder insert strips,extra st...",0.000168,central,chicago,illinois,united states,corporate,sh-19975,1
9796,ca-2016-128608,12/01/2016,standard class,office supplies,art,"bic brite liner highlighters, chisel tip",0.000458,east,toledo,ohio,united states,corporate,cs-12490,1
9797,ca-2016-128608,12/01/2016,standard class,technology,phones,ge 30524ee4,0.010389,east,toledo,ohio,united states,corporate,cs-12490,2
9798,ca-2016-128608,12/01/2016,standard class,technology,phones,anker 24w portable micro usb car charger,0.001165,east,toledo,ohio,united states,corporate,cs-12490,1
9799,ca-2016-128608,12/01/2016,standard class,technology,accessories,sandisk cruzer 4 gb usb flash drive,0.000459,east,toledo,ohio,united states,corporate,cs-12490,1

In [24]:
# Convert "Order Date" and "Ship Date" columns to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Calculate the number of days in the studied period
studied_period_days = (df['Ship Date'] - df['Order Date']).max().days
print("studied_period_days : ", studied_period_days)

# Calculate the number of weeks in the studied period
studied_period_weeks = studied_period_days // 7
print("studied_period_weeks : ", studied_period_weeks)

<ipython-input-24-902524aeec07>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order Date'] = pd.to_datetime(df['Order Date'])

KeyError: ignored

In [25]:
# Check how many ship modes we have
num_ship_modes = df['Ship Mode'].nunique()
print("num_ship_modes : ", num_ship_modes)

num_ship_modes :  4

In [26]:
# Calculate the customer who requests the most
most_orders_customer = df['Customer ID'].value_counts().idxmax()

# Calculate the customer who spends the most
customer_spending = df.groupby('Customer ID')['Sales'].sum()
spends_most_customer = customer_spending.idxmax()

# Calculate the customer who cares the most about deliveries (assumes 'Ship Mode' reflects delivery preference)
most_cares_customer = df['Ship Mode'].value_counts().idxmax()

# Calculate the total number of unique customers
total_customers = df['Customer ID'].nunique()

# Calculate the portion of these users among the total users
portion_most_orders = df['Customer ID'].value_counts().max() / total_customers
portion_spends_most = customer_spending.max() / customer_spending.sum()
portion_most_cares = df['Ship Mode'].value_counts().max() / total_customers

print("Customer who requests the most:", most_orders_customer)
print("Customer who spends the most:", spends_most_customer)
print("Customer who cares the most about deliveries:", most_cares_customer)

print("Portion of most orders customer among total customers:", portion_most_orders)
print("Portion of spends most customer among total spending customers:", portion_spends_most)
print("Portion of most cares customer among total customers:", portion_most_cares)

Customer who requests the most: wb-21850
Customer who spends the most: sm-20320
Customer who cares the most about deliveries: standard class
Portion of most orders customer among total customers: 0.044136191677175286
Portion of spends most customer among total spending customers: 0.011074843594181878
Portion of most cares customer among total customers: 7.387137452711223

In [27]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df['Order Ship Period'] = (df['Ship Date'] - df['Order Date']).dt.days

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0        1.0  ca-2017-152156 2017-08-11 2017-11-11    second class
1        2.0  ca-2017-152156 2017-08-11 2017-11-11    second class
2        3.0  ca-2017-138688 2017-12-06 2017-06-16    second class
3        4.0  us-2016-108966 2016-11-10 2016-10-18  standard class
4        5.0  us-2016-108966 2016-11-10 2016-10-18  standard class
...      ...             ...        ...        ...             ...
9795  9796.0  ca-2017-125920 2017-05-21 2017-05-28  standard class
9796  9797.0  ca-2016-128608 2016-12-01 2016-01-17  standard class
9797  9798.0  ca-2016-128608 2016-12-01 2016-01-17  standard class
9798  9799.0  ca-2016-128608 2016-12-01 2016-01-17  standard class
9799  9800.0  ca-2016-128608 2016-12-01 2016-01-17  standard class

     Customer ID    Segment        Country             City       State  \
0       cg-12520   consumer  united states        henderson    kentucky
1       cg-12520   consumer  united states        henderson    kentucky
2       dv-13045  corporate  united states      los angeles  california
3       so-20335   consumer  united states  fort lauderdale     florida
4       so-20335   consumer  united states  fort lauderdale     florida
...          ...        ...            ...              ...         ...
9795    sh-19975  corporate  united states          chicago    illinois
9796    cs-12490  corporate  united states           toledo        ohio
9797    cs-12490  corporate  united states           toledo        ohio
9798    cs-12490  corporate  united states           toledo        ohio
9799    cs-12490  corporate  united states           toledo        ohio

       Region       Product ID         Category Sub-Category  \
0       south  fur-bo-10001798        furniture    bookcases
1       south  fur-ch-10000454        furniture       chairs
2        west  off-la-10000240  office supplies       labels
3       south  fur-ta-10000577        furniture       tables
4       south  off-st-10000760  office supplies      storage
...       ...              ...              ...          ...
9795  central  off-bi-10003429  office supplies      binders
9796     east  off-ar-10001374  office supplies          art
9797     east  tec-ph-10004977       technology       phones
9798     east  tec-ph-10000912       technology       phones
9799     east  tec-ac-10000487       technology  accessories

                                           Product Name     Sales  \
0                     bush somerset collection bookcase  0.011571
1     hon deluxe fabric upholstered stacking chairs,...  0.032332
2     self-adhesive address labels for typewriters b...  0.000646
3         bretford cr4500 series slim rectangular table  0.042299
4                        eldon fold 'n roll cart system  0.000988
...                                                 ...       ...
9795  cardinal holdit! binder insert strips,extra st...  0.000168
9796           bic brite liner highlighters, chisel tip  0.000458
9797                                        ge 30524ee4  0.010389
9798           anker 24w portable micro usb car charger  0.001165
9799                sandisk cruzer 4 gb usb flash drive  0.000459

      Sale Interest  Order Ship Period
0                 2                 92
1                 3                 92
2                 1               -173
3                 3                -23
4                 1                -23
...             ...                ...
9795              1                  7
9796              1               -319
9797              2               -319
9798              1               -319
9799              1               -319

[9800 rows x 18 columns]

In [ ]:
# Group products by category and find the category with the highest sales:
category_sales = df.groupby('Category')['Sales'].sum()
highest_sales_category = category_sales.idxmax()
num_customers_in_highest_sales_category = df[df['Category'] == highest_sales_category]['Customer ID'].nunique()

In [ ]:
# Analyze the 'Segment' column and suggest which segment should have more focus:
segment_focus = df['Segment'].value_counts().idxmax()

consumer

In [ ]:
# Filter records in the period [X, Y] and calculate the sales average:
start_date = pd.to_datetime('X')
end_date = pd.to_datetime('Y')
filtered_data = df[(df['Order Date'] >= start_date) & (df['Order Date'] <= end_date)]
sales_average = filtered_data['Sales'].mean()

In [ ]:
# Filter records with 'Sales' less than Y, group by city, and identify cities with lower priorities:
Y = 100  # Replace with your threshold value
filtered_data = df[df['Sales'] < Y]
low_priority_cities = filtered_data.groupby('City').size().idxmax()

In [ ]:
# Count how many times 'Sales' has a value more than Y for a specific city (X):
X = 'CityName'  # Replace with the city you want to analyze
Y = 100  # Replace with your threshold value
count_sales_above_threshold = len(df[(df['City'] == X) & (df['Sales'] > Y)])

In [ ]:
# Analyze changes in sales (days and weeks), create and display a series representing the difference in sales:
daily_sales_diff = df.groupby(['Region', pd.Grouper(key='Order Date', freq='D')])['Sales'].sum().diff()
weekly_sales_diff = df.groupby(['Region', pd.Grouper(key='Order Date', freq='W')])['Sales'].sum().diff()

In [ ]:
# Insert new data with the same structure and ensure ordered indexes:

# (a) Insert new data into the existing DataFrame
new_data = pd.read_csv('new_data.csv')  # Load the new data
df = pd.concat([df, new_data], ignore_index=True)

# (b) Ensure that indexes are ordered
df = df.sort_index()

In [ ]:
print(df['Row ID'])  # Display a specific column

0          1
1          2
2          3
3          4
4          5
        ...
9795    9796
9796    9797
9797    9798
9798    9799
9799    9800
Name: Row ID, Length: 9800, dtype: int64

In [ ]:
print(df.sample())

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
5917    5918  US-2016-126977  17/09/2016  23/09/2016  Standard Class

     Customer ID Customer Name   Segment        Country           City  \
5917    PF-19120  Peter Fuller  Consumer  United States  New York City

         State  Postal Code Region       Product ID   Category Sub-Category  \
5917  New York      10035.0   East  FUR-BO-10004834  Furniture    Bookcases

                                           Product Name     Sales
5917  Riverside Palais Royal Lawyers Bookcase, Royal...  4228.704

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB
None

**.loc[] - Label-Based Selection**

In [ ]:
# Create a sample DataFrame
data = {'A': [1, 2, 3, 4],
        'B': [5, 6, 7, 8]}
df = pd.DataFrame(data, index=['Row1', 'Row2', 'Row3', 'Row4'])

# Select a single element by label
value = df.loc['Row2', 'A']
print(value)

# Select an entire row by label
row = df.loc['Row3']
print(row)

# Select specific columns for a row
subset = df.loc['Row1', ['A', 'B']]
print(subset)

2
A    3
B    7
Name: Row3, dtype: int64
A    1
B    5
Name: Row1, dtype: int64

**.iloc[] - Integer-Based Selection**

In [ ]:
# Create a sample DataFrame
data = {'A': [1, 2, 3, 4],
        'B': [5, 6, 7, 8]}
df = pd.DataFrame(data)
print(df)

# Select a single element by position
value = df.iloc[1, 0]
print(value)

# Select an entire row by position
row = df.iloc[2]
print(row)

# Select specific columns for a row
subset = df.iloc[0, [0, 1]]
print(subset)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8
2
A    3
B    7
Name: 2, dtype: int64
A    1
B    5
Name: 0, dtype: int64

In [ ]:
# Boolean indexing with .loc[]
selected_rows = df.loc[df['A'] > 2]
print("selected_rows : ",selected_rows)

# Slicing with .iloc[]
sliced_data = df.iloc[1:3, 0:2]
print("sliced_data : ",sliced_data)

# Combining .loc[] and .iloc[] for mixed label and integer-based selections
mixed_selection = df.loc['Row1':'Row2', 'A':'B']
print("mixed_selection : ",mixed_selection)

selected_rows :     A  B
2  3  7
3  4  8
sliced_data :     A  B
1  2  6
2  3  7
mixed_selection :  Empty DataFrame
Columns: [A, B]
Index: []

**Handling Missing Data:**

**dropna()**

In [ ]:
import numpy as np
# Create a sample DataFrame with missing data
data = {'A': [1, 2, np.nan, 4],
        'B': [5, np.nan, 7, 8]}
df = pd.DataFrame(data)

# Remove rows with missing values
df_cleaned = df.dropna(axis=0)
# print(df_cleaned)

# Remove columns with missing values
df_cleaned = df.dropna(axis=1)
print(df_cleaned)

# Remove rows where all values are missing
df_cleaned = df.dropna(how='all')
# print(df_cleaned)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

**fillna()**

In [ ]:
# Fill missing values with a specific value
df_filled = df.fillna(value=0)

# Fill missing values with the mean of each column
df_filled = df.fillna(df.mean())

# Forward fill missing values
df_filled = df.ffill()

# Forward Fill (ffill):

# In forward fill, missing values are filled with the most recent non-missing value that occurs before the missing value in the DataFrame or Series.
# It essentially propagates the last observed value forward to fill the missing value.
# This method is particularly useful when dealing with time series data where values are collected at regular intervals, and missing values should be interpolated using the most recent known value.
# Example:
# If you have a Series with missing values like this:
# 1   10.0
# 2    NaN
# 3    NaN
# 4   20.0
# After applying forward fill, it will become:

# 1   10.0
# 2   10.0
# 3   10.0
# 4   20.0

# Backward fill missing values
df_filled = df.bfill()

# Backward Fill (bfill):

# In backward fill, missing values are filled with the next non-missing value that occurs after the missing value in the DataFrame or Series.
# It propagates the next observed value backward to fill the missing value.
# Backward fill is useful when you want to carry forward the next observed value to fill the gaps in your data.

# Example:
# If you have a Series with missing values like this:

# 1    NaN
# 2    NaN
# 3   30.0
# 4   40.0
# After applying backward fill, it will become:

# 1   30.0
# 2   30.0
# 3   30.0
# 4   40.0

**interpolate() - Interpolating Missing Data:**

In [ ]:
# Interpolate missing values linearly
df_interpolated = df.interpolate(method='linear')

# Interpolate missing values with a polynomial method
df_interpolated = df.interpolate(method='polynomial', order=2)

# In the code you provided, you are using the `interpolate` method in pandas to fill missing values in a DataFrame (`df`) using different interpolation methods. The two methods you're using are "linear" interpolation and "polynomial" interpolation with a specified order.

# 1. Linear Interpolation (`method='linear'`):
#    - Linear interpolation is a method for filling missing values by estimating them as points along a straight line between neighboring non-missing values.
#    - In the context of time series or numerical data, this means that the missing values are estimated as values that create a linear trend between the available data points.
#    - Linear interpolation is suitable when you assume a linear relationship between the data points.

#    Example:
#    If you have a Series with missing values like this:
#    ```
#    1   10.0
#    2    NaN
#    3    NaN
#    4   20.0
#    ```
#    After applying linear interpolation, it will become:
#    ```
#    1   10.0
#    2   13.3  # Estimated linearly
#    3   16.7  # Estimated linearly
#    4   20.0
#    ```

# 2. Polynomial Interpolation (`method='polynomial'`, `order=2`):
#    - Polynomial interpolation is a more flexible method that estimates missing values using a polynomial function of a specified order.
#    - In your code, you've specified an order of 2, which means the interpolation function is a quadratic polynomial.
#    - This method can capture more complex relationships in the data when linear interpolation may not be sufficient.

#    Example:
#    If you have a Series with missing values like this:
#    ```
#    1    5.0
#    2    NaN
#    3    NaN
#    4   13.0
#    ```
#    After applying polynomial interpolation with order 2, it will become:
#    ```
#    1   5.0
#    2   6.0  # Estimated using a quadratic polynomial
#    3   8.0  # Estimated using a quadratic polynomial
#    4  13.0
#    ```

# The choice between linear and polynomial interpolation, as well as the order of the polynomial, depends on the nature of your data and the assumptions you want to make about the relationship between data points. Linear interpolation is simple and often sufficient, but polynomial interpolation allows you to capture more complex patterns when they exist in the data.

**Removing Duplicate Rows:**

In [ ]:
# Create a sample DataFrame with duplicate rows
data = {'A': [1, 2, 2, 3],
        'B': [4, 5, 5, 6]}
df = pd.DataFrame(data)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()

# Remove duplicates based on a specific column
df_no_duplicates = df.drop_duplicates(subset='A')

**Renaming Columns:**

In [ ]:
# Create a sample DataFrame
data = {'OldName1': [1, 2, 3],
        'OldName2': [4, 5, 6]}
df = pd.DataFrame(data)

# Rename columns
df = df.rename(columns={'OldName1': 'NewName1', 'OldName2': 'NewName2'})