In [ ]:
#from google.colab import drive
#drive.mount('/content/gdrive')
import pandas as pd
dataset = pd.read_csv('/content/train.csv')

print("Columns:", dataset.columns)
print("Number of Rows:", len(dataset))
statistics = dataset.describe()
print("Averaged Numbers, Max/Min Values:\n", statistics)
missing_values = dataset.isna().sum()
print("Number of Missing Values per Column:\n", missing_values)


# Display the first 10 rows of the dataset
first_10_rows = dataset.head(10)
print("First 10 Rows of the Dataset:\n", first_10_rows)

# Number of unique values per column
unique_values = dataset.nunique()

# Data types of values in each column
data_types = dataset.dtypes

print("Number of Unique Values per Column:\n", unique_values)
print("Data Types of Values in Each Column:\n", data_types)

# Group the dataset by a specific column (e.g., "order date") and calculate averages
grouped_data = dataset.groupby('order_date').mean()

# Find the row with the highest average
#row_with_highest_average = grouped_data.mean().idxmax()

# Define the desired order of columns
#desired_columns = ['important_column1', 'important_column2', 'important_column3', 'other_column1', 'other_column2']

# Create a new DataFrame with columns in the desired order
#rearranged_dataset = dataset[desired_columns]

Columns: Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')
Number of Rows: 9800
Averaged Numbers, Max/Min Values:
             Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000
Number of Missing Values per Column:
 Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64
First 10 Rows of the Dataset:
    Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
5       6  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
6       7  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
7       8  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
8       9  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710
9      10  CA-2015-115812  09/06/2015  14/06/2015  Standard Class    BH-11710

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
5  Brosina Hoffman   Consumer  United States      Los Angeles  California
6  Brosina Hoffman   Consumer  United States      Los Angeles  California
7  Brosina Hoffman   Consumer  United States      Los Angeles  California
8  Brosina Hoffman   Consumer  United States      Los Angeles  California
9  Brosina Hoffman   Consumer  United States      Los Angeles  California

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage
5      90032.0   West  FUR-FU-10001487        Furniture  Furnishings
6      90032.0   West  OFF-AR-10002833  Office Supplies          Art
7      90032.0   West  TEC-PH-10002275       Technology       Phones
8      90032.0   West  OFF-BI-10003910  Office Supplies      Binders
9      90032.0   West  OFF-AP-10002892  Office Supplies   Appliances

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680
5  Eldon Expressions Wood and Plastic Desk Access...   48.8600
6                                         Newell 322    7.2800
7                     Mitel 5320 IP Phone VoIP phone  907.1520
8  DXL Angle-View Binders with Locking Rings by S...   18.5040
9                   Belkin F5C206VTEL 6 Outlet Surge  114.9000
Number of Unique Values per Column:
 Row ID           9800
Order ID         4922
Order Date       1230
Ship Date        1326
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              529
State              49
Postal Code       626
Region              4
Product ID       1861
Category            3
Sub-Category       17
Product Name     1849
Sales            5757
dtype: int64
Data Types of Values in Each Column:
 Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

KeyError: ignored

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)