In [12]:
import pandas as pd
import numpy as np

# Load the dataset with unnamed columns
dataset = pd.read_csv('/content/oil-spill.csv', header=None)

# Rename the columns as col1, col2, ...
dataset.columns = [f'col{i}' for i in range(1, len(dataset.columns) + 1)]

# 3.1 Visual analysis of the dataset
print("Dataset Preview:")
print(dataset.head())

# 3.2 Identify columns with a single value
single_value_columns = dataset.columns[dataset.nunique() == 1]
print("\nColumns with a single value:")
print(single_value_columns)

# 3.3 function to summarize the number of unique values for each column
def summarize_unique_values(data):
    unique_counts = data.nunique()
    return unique_counts

# 4. Remove columns containing a single value
def remove_single_value_columns(data):
    single_value_columns = data.columns[data.nunique() == 1]
    data = data.drop(columns=single_value_columns)
    return data

# 5. Consider columns with very few unique values
# 5.1 Write code to calculate the percentage of unique values
def calculate_percentage_unique_values(data):
    total_rows = len(data)
    percentage_unique_values = (data.nunique() / total_rows) * 100
    filtered_percentages = percentage_unique_values[percentage_unique_values > 1]
    return filtered_percentages

# Example Usage:
# Summary of unique values for each column
summary_unique_values = summarize_unique_values(dataset)
print("\nSummary of unique values for each column:")
print(summary_unique_values)

# Remove columns with a single value
dataset_removed_single_value_columns = remove_single_value_columns(dataset)
print("\nDataset after removing columns with a single value:")
print(dataset_removed_single_value_columns)

# Calculate the percentage of unique values for each column
percentage_unique_values = calculate_percentage_unique_values(dataset)
print("\nPercentage of unique values for each column:")
print(percentage_unique_values)

Dataset Preview:
   col1   col2     col3    col4  col5        col6   col7  col8     col9  \
0     1   2558  1506.09  456.63    90   6395000.0  40.88  7.89  29780.0
1     2  22325    79.11  841.03   180  55812500.0  51.11  1.21  61900.0
2     3    115  1449.85  608.43    88    287500.0  40.42  7.34   3340.0
3     4   1201  1562.53  295.65    66   3002500.0  42.40  7.97  18030.0
4     5    312   950.27  440.86    37    780000.0  41.43  7.03   3350.0

   col10  ...    col41     col42    col43    col44  col45  col46     col47  \
0   0.19  ...  2850.00   1000.00   763.16   135.46   3.73      0  33243.19
1   0.02  ...  5750.00  11500.00  9593.48  1648.80   0.60      0  51572.04
2   0.18  ...  1400.00    250.00   150.00    45.13   9.33      1  31692.84
3   0.19  ...  6041.52    761.58   453.21   144.97  13.33      1  37696.21
4   0.17  ...  1320.04    710.63   512.54   109.16   2.58      0  29038.17

   col48  col49  col50
0  65.74   7.95      1
1  65.73   6.26      0
2  65.81   7.84      1
3  65.67   8.07      1
4  65.66   7.35      0

[5 rows x 50 columns]

Columns with a single value:
Index(['col23'], dtype='object')

Summary of unique values for each column:
col1     238
col2     297
col3     927
col4     933
col5     179
col6     375
col7     820
col8     618
col9     561
col10     57
col11    577
col12     59
col13     73
col14    107
col15     53
col16     91
col17    893
col18    810
col19    170
col20     53
col21     68
col22      9
col23      1
col24     92
col25      9
col26      8
col27      9
col28    308
col29    447
col30    392
col31    107
col32     42
col33      4
col34     45
col35    141
col36    110
col37      3
col38    758
col39      9
col40      9
col41    388
col42    220
col43    644
col44    649
col45    499
col46      2
col47    937
col48    169
col49    286
col50      2
dtype: int64

Dataset after removing columns with a single value:
     col1   col2     col3    col4  col5        col6   col7   col8     col9  \
0       1   2558  1506.09  456.63    90   6395000.0  40.88   7.89  29780.0
1       2  22325    79.11  841.03   180  55812500.0  51.11   1.21  61900.0
2       3    115  1449.85  608.43    88    287500.0  40.42   7.34   3340.0
3       4   1201  1562.53  295.65    66   3002500.0  42.40   7.97  18030.0
4       5    312   950.27  440.86    37    780000.0  41.43   7.03   3350.0
..    ...    ...      ...     ...   ...         ...    ...    ...      ...
932   200     12    92.42  364.42   135     97200.0  59.42  10.34    884.0
933   201     11    98.82  248.64   159     89100.0  59.64  10.18    831.0
934   202     14    25.14  428.86    24    113400.0  60.14  17.94    847.0
935   203     10    96.00  451.30    68     81000.0  59.90  15.01    831.0
936   204     11     7.73  235.73   135     89100.0  61.82  12.24    831.0

     col10  ...    col41     col42    col43    col44  col45  col46     col47  \
0     0.19  ...  2850.00   1000.00   763.16   135.46   3.73      0  33243.19
1     0.02  ...  5750.00  11500.00  9593.48  1648.80   0.60      0  51572.04
2     0.18  ...  1400.00    250.00   150.00    45.13   9.33      1  31692.84
3     0.19  ...  6041.52    761.58   453.21   144.97  13.33      1  37696.21
4     0.17  ...  1320.04    710.63   512.54   109.16   2.58      0  29038.17
..     ...  ...      ...       ...      ...      ...    ...    ...       ...
932   0.17  ...   381.84    254.56    84.85   146.97   4.50      0   2593.50
933   0.17  ...   284.60    180.00   150.00    51.96   1.90      0   4361.25
934   0.30  ...   402.49    180.00   180.00     0.00   2.24      0   2153.05
935   0.25  ...   402.49    180.00    90.00    73.48   4.47      0   2421.43
936   0.20  ...   254.56    254.56   127.28   180.00   2.00      0   3782.68

     col48  col49  col50
0    65.74   7.95      1
1    65.73   6.26      0
2    65.81   7.84      1
3    65.67   8.07      1
4    65.66   7.35      0
..     ...    ...    ...
932  65.85   6.39      0
933  65.70   6.53      0
934  65.91   6.12      0
935  65.97   6.32      0
936  65.65   6.26      0

[937 rows x 49 columns]

Percentage of unique values for each column:
col1      25.400213
col2      31.696905
col3      98.932764
col4      99.573106
col5      19.103522
col6      40.021345
col7      87.513340
col8      65.955176
col9      59.871932
col10      6.083244
col11     61.579509
col12      6.296692
col13      7.790822
col14     11.419424
col15      5.656350
col16      9.711846
col17     95.304162
col18     86.446105
col19     18.143010
col20      5.656350
col21      7.257204
col24      9.818570
col28     32.870864
col29     47.705443
col30     41.835646
col31     11.419424
col32      4.482391
col34      4.802561
col35     15.048026
col36     11.739594
col38     80.896478
col41     41.408751
col42     23.479189
col43     68.729989
col44     69.263607
col45     53.255069
col47    100.000000
col48     18.036286
col49     30.522946
dtype: float64